version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/nette
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    networks:
      - nette-network
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: php
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/nette
    networks:
      - nette-network
  database:
    container_name: database
    image: mysql:8.0
    hostname: mysql
    ports:
      - '3306:3306'
    volumes:
      - database_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nette-network
networks:
  nette-network:
    driver: bridge
volumes:
  database_data:
