on:
  push:
    branches:
      - dev

name: CI Branch Dev

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: php:8.2-fpm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Composer
        run: |
          apt-get update
          apt-get install -y unzip
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Run PHPstan (Static Analysis Tool)
        run: |
          composer phpstan